# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: book_store_events.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'book_store_events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x62ook_store_events.proto\x12\x06\x65vents\"H\n\x0c\x45ventRequest\x12\x12\n\nevent_type\x18\x01 \x01(\t\x12\x12\n\nevent_data\x18\x02 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x03 \x01(\t\"\x1f\n\rEventResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2J\n\x0c\x45ventService\x12:\n\x0bReportEvent\x12\x14.events.EventRequest\x1a\x15.events.EventResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_store_events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTREQUEST']._serialized_start=35
  _globals['_EVENTREQUEST']._serialized_end=107
  _globals['_EVENTRESPONSE']._serialized_start=109
  _globals['_EVENTRESPONSE']._serialized_end=140
  _globals['_EVENTSERVICE']._serialized_start=142
  _globals['_EVENTSERVICE']._serialized_end=216
# @@protoc_insertion_point(module_scope)
